import React, { useState, useEffect } from "react";
import axios from "axios";
import "./StepDormitory.css";

const API_URL = process.env.REACT_APP_API_URL; // Your API base URL

const StepDormitory = ({ data, sexe, onChange, onNext, onPrevious }) => {
  const [dortoirs, setDortoirs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [apiError, setApiError] = useState("");

  // Fetch dormitories from API
  useEffect(() => {
    const fetchDormitories = async () => {
      try {
        setLoading(true);
        setApiError("");
        setError(""); // Clear previous errors

        // API call to get dormitories by gender
        const response = await axios.get(`${API_URL}/api/v1/registrations/dortoirs`, {
          params: { sexe: sexe }
        });

        console.log('Raw API response:', response.data); // Debug: Remove in production

        // Handle common API response formats and extract array
        let dortoirsData = [];
        if (Array.isArray(response.data)) {
          // Direct array response
          dortoirsData = response.data;
        } else if (response.data.dormitories && Array.isArray(response.data.dormitories)) {
          // Wrapped as { dormitories: [...] }
          dortoirsData = response.data.dormitories;
        } else if (response.data.data && Array.isArray(response.data.data)) {
          // Wrapped as { data: [...] }
          dortoirsData = response.data.data;
        } else {
          // Unexpected format
          console.error('Unexpected API structure:', response.data);
          setApiError("Invalid data format from server. Please contact support.");
          setLoading(false);
          return;
        }

        // Optional: Filter by sexe if backend doesn't (uncomment if needed)
        // const filteredDortoirs = dortoirsData.filter(d => d.sexe === sexe);
        // setDortoirs(filteredDortoirs);

        setDortoirs(dortoirsData);
        setLoading(false);

      } catch (err) {
        console.error("Error fetching dormitories:", err);
        setApiError(
          err.response?.data?.message || 
          "Unable to load dormitories. Please try again."
        );
        setLoading(false);
        setDortoirs([]); // Ensure array state on error
      }
    };

    if (sexe) {
      fetchDormitories();
    } else {
      setDortoirs([]);
      setLoading(false);
    }
  }, [sexe]); // Re-fetch if sexe changes

  const handleDormitorySelect = (dortoir) => {
    const available = dortoir.available || 0;

    // Do nothing if dormitory is full
    if (available <= 0) {
      setError(`The dormitory "${dortoir.name}" is full. Please choose another.`);
      return;
    }

    // If clicking the already selected dormitory, deselect it
    if (data.dortoirId === dortoir.code) {
      onChange({
        dortoir: '',
        dortoirId: '',
        dortoirCode: '',
        // matricule: ''
      });
      setError('');
      return;
    }

    // Otherwise, select the new dormitory
    onChange({
      dortoir: dortoir.name,
      dortoirId: dortoir.code,
      dortoirCode: dortoir.code,
      matricule: '', // Will be generated by backend
    });
    setError('');
    
    console.log('Selected dormitory:', dortoir.name, dortoir.code); // Debug: Optional
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!data.dortoir) {
      setError("Please select a dormitory");
      return;
    }
    onNext();
  };

  // Loading state
  if (loading) {
    return (
      <div className="step-form">
        <div className="loading-spinner">
          <div className="spinner"></div>
          <p>Loading available dormitories...</p>
        </div>
      </div>
    );
  }

  // API error state
  if (apiError) {
    return (
      <div className="step-form">
        <div className="error-container">
          <div className="error-icon">⚠️</div>
          <h3>Connection Error</h3>
          <p>{apiError}</p>
          <div className="form-actions">
            <button
              type="button"
              className="btn btn-secondary"
              style={{margin: "0 5px"}}
              onClick={onPrevious}
            >
              ← Previous
            </button>
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => window.location.reload()}
            >
              Retry
            </button>
          </div>
        </div>
      </div>
    );
  }

  // All dormitories full check (with array guard)
  const allFull = Array.isArray(dortoirs) && dortoirs.length > 0 && dortoirs.every(d => (d.available || 0) === 0);

  if (allFull) {
    return (
      <div className="step-form">
        <div className="no-availability-container">
          <div className="icon-large">🏠</div>
          <h3>No Dormitories Available</h3>
          <p>
            All {sexe === "M" ? "male" : "female"} dormitories are currently full.
          </p>
          <div className="info-card">
            <p>
              <strong>What to do?</strong><br />
              - Contact us at <a href="tel:+225XXXXXXXX">+225 XX XX XX XX</a><br />
              - Send an email to <a href="mailto:contact@annour.ci">contact@annour.ci</a><br />
              - Try again later
            </p>
          </div>
          <div className="form-actions">
            <button
              type="button"
              className="btn btn-secondary"
              style={{margin: "0 5px"}}
              onClick={onPrevious}
            >
              ← Previous
            </button>
          </div>
        </div>
      </div>
    );
  }

  // Normal display of dormitories (with array guard)
  return (
    <div className="step-form">
      <div className="step-header">
        <h2>🏠 Dormitory Selection</h2>
        <p>Select your dormitory from the available options</p>
      </div>

      {error && (
        <div className="alert alert-error">
          <span>⚠️</span>
          <span>{error}</span>
        </div>
      )}

      <form onSubmit={handleSubmit}>
        <div className="dormitory-grid">
          {Array.isArray(dortoirs) && dortoirs.length > 0 ? (
            dortoirs.map((dortoir) => {
              const available = dortoir.available || 0;
              const capacity = dortoir.capacity || 30;
              const isAvailable = available > 0;
              const isSelected = data.dortoirId === dortoir.code;
              const occupancyPercent = ((capacity - available) / capacity) * 100;

              return (
                <div
                  key={dortoir.code}
                  className={`dormitory-card ${!isAvailable ? "disabled" : ""} ${
                    isSelected ? "selected" : ""
                  }`}
                  onClick={() => isAvailable && handleDormitorySelect(dortoir)}
                >
                  <div className="dormitory-card-header">
                    <h3 className="dormitory-name">{dortoir.name}</h3>
                    {isSelected && (
                      <span className="selected-badge">✓ Selected</span>
                    )}
                  </div>

                  <div className="dormitory-capacity">
                    <div className="capacity-text">
                      <span className="available-count">{available}</span>
                      <span className="capacity-total">/{capacity}</span>
                      <span className="capacity-label">places available</span>
                    </div>

                    <div className="capacity-bar">
                      <div
                        className={`capacity-fill ${
                          occupancyPercent > 80 ? "critical" : ""
                        }`}
                        style={{ width: `${Math.min(occupancyPercent, 100)}%` }}
                      ></div>
                    </div>
                  </div>

                  <div
                    className={`availability-status ${
                      isAvailable ? "available" : "full"
                    }`}
                  >
                    {isAvailable ? "✓ Available" : "✗ Full"}
                  </div>
                </div>
              );
            })
          ) : (
            <p>No dormitories found. Please check your selection.</p>
          )}
        </div>

        <div className="form-actions">
          <button
            type="button"
            className="btn btn-secondary"
            style={{margin: "0 5px"}}
            onClick={onPrevious}
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Previous
          </button>
          <button 
            type="submit" 
            className="btn btn-primary"
            style={{margin: "0 5px"}}
            disabled={!data.dortoir}
          >
            Continue
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </div>
      </form>
    </div>
  );
};

export default StepDormitory;
